//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessary_Big
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ProductName { get; set; }
        public int Price { get; set; }
        public int KeyPrice { get; set; }
        public int Discount { get; set; }
        public int CountImport { get; set; }
        public int CountExport { get; set; }
        public string Model { get; set; }
    }
}
