//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acessary_Log_Key
    {
        public long Id { get; set; }
        public string Id_Akey { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public int Count { get; set; }
        public string Code { get; set; }
        public string Accessary { get; set; }
        public int Type { get; set; }
    }
}
