//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class B_Log_Active
    {
        public long Id { get; set; }
        public string Model { get; set; }
        public string ProductCode { get; set; }
        public string Process { get; set; }
        public Nullable<long> ProcessId { get; set; }
        public string Unit { get; set; }
        public int Quantity { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> CheckActive { get; set; }
    }
}
