//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_OderItems
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public Nullable<long> ProductId { get; set; }
        public string Product { get; set; }
        public string ProductCode { get; set; }
        public string ProductThumnail { get; set; }
        public int Quantity { get; set; }
        public string ProductUnit { get; set; }
        public int ListedPrice { get; set; }
        public int Price { get; set; }
        public int Discount { get; set; }
        public int Amount { get; set; }
        public int Total { get; set; }
    }
}
