//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Order
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string Agent_Id { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Createby { get; set; }
        public Nullable<System.DateTime> Checkdate { get; set; }
        public string Checkby { get; set; }
        public string LinkFile { get; set; }
        public int Quantity { get; set; }
        public int Amount { get; set; }
        public int Discount { get; set; }
        public int Total { get; set; }
    }
}
