//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Order_Log
    {
        public long Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string User_Id { get; set; }
        public Nullable<long> Id_Order { get; set; }
    }
}
