//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Product
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string LongDescription { get; set; }
        public int ListedPrice { get; set; }
        public int Price { get; set; }
        public string Discount { get; set; }
        public string Banner { get; set; }
        public string Thumnails { get; set; }
        public string Details { get; set; }
        public string Link { get; set; }
        public bool Status { get; set; }
        public int Sort { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public bool IsNew { get; set; }
        public string Limited { get; set; }
        public string Trademark { get; set; }
        public string Model { get; set; }
        public string Unit { get; set; }
        public string Tech { get; set; }
        public string Watt { get; set; }
        public string Size { get; set; }
        public string Volt { get; set; }
        public string Madein { get; set; }
        public string Apply { get; set; }
        public string Util { get; set; }
        public string Another { get; set; }
        public Nullable<long> Cate { get; set; }
    }
}
