//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOG_MO
    {
        public long Id { get; set; }
        public string User_Id { get; set; }
        public string Service_Id { get; set; }
        public string Request_Id { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public Nullable<int> Status { get; set; }
        public string Response { get; set; }
    }
}
