//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string ProductCate { get; set; }
        public string Serial { get; set; }
        public string Code { get; set; }
        public string Model { get; set; }
        public string Trademark { get; set; }
        public int Limited { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Createby { get; set; }
        public string Active_phone { get; set; }
        public string Active_code { get; set; }
        public Nullable<System.DateTime> Customer_date { get; set; }
        public Nullable<System.DateTime> Active_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
        public string Active_by { get; set; }
        public string Active_chanel { get; set; }
        public Nullable<System.DateTime> Buydate { get; set; }
        public string BuyAdr { get; set; }
        public Nullable<System.DateTime> Exportdate { get; set; }
        public string AgentC1 { get; set; }
        public Nullable<System.DateTime> Importdate { get; set; }
        public string AgentC2 { get; set; }
        public string Importchanel { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Wait_date { get; set; }
        public int Wait_day { get; set; }
    }
}
