//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentNotifi
    {
        public long ID { get; set; }
        public string UserName { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Result { get; set; }
        public string Status { get; set; }
    }
}
