//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warranti
    {
        public long Id { get; set; }
        public int Status { get; set; }
        public string Code { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
        public string Createby { get; set; }
        public string Chanel { get; set; }
        public string Phone { get; set; }
        public string PhoneExtra { get; set; }
        public string Address { get; set; }
        public string Ward { get; set; }
        public string District { get; set; }
        public string Province { get; set; }
        public string Cate { get; set; }
        public string Note { get; set; }
        public string Extra { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public string Station_Warranti { get; set; }
        public string KTV_Warranti { get; set; }
        public Nullable<System.DateTime> Successdate { get; set; }
        public string Successnote { get; set; }
        public string SuccessExtra { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public string KM { get; set; }
        public int Price_Move { get; set; }
        public int Price_Accessary { get; set; }
        public string Price_Cate { get; set; }
        public int Price { get; set; }
        public int Amount { get; set; }
        public string Sign { get; set; }
        public string ProductCode { get; set; }
        public string Model { get; set; }
        public string Serial { get; set; }
        public string Warranti_Cate { get; set; }
        public Nullable<System.DateTime> Buydate { get; set; }
        public string BuyAdr { get; set; }
        public string ProductName { get; set; }
    }
}
